# k8s/service.yaml
# Exposes the Gradio UI via NLB during the demo window.
apiVersion: v1
kind: Service
metadata:
  name: buybox-propensity-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: buybox-propensity-api
  ports:
    - port: 80
      targetPort: 7860
      protocol: TCP
